import * as fs from 'fs/promises'
import * as path from 'path'
import yaml from 'js-yaml'
import { ObsidianVault } from '@/knowledge/vault'
import { resolveProjectRoot } from '@/knowledge/paths'
import {
  loadDomainProfile,
  saveDomainProfile,
  inferOverviewPagesFromWiki,
  profilePath as profilePathFn,
} from '@/harness/profile'
import {
  projectAgentsMd,
  cursorRuleMdc,
  claudeMd,
  cursorHooksJson,
  cursorSessionStartHook,
  cursorBeforePromptHook,
  claudeSettingsJson,
  claudeSessionStartHook,
  claudeBeforePromptHook,
  codexHooksJson,
  windsurfRuleMd,
  windsurfHooksJson,
  windsurfBeforePromptHook,
  continueRuleMd,
  continueSettingsJson,
  opencodeHarnessPlugin,
  mcpJsonCursor,
  mcpJsonClaude,
  opencodeJson,
  codexToml,
  windsurfMcpJson,
  continueMcpYaml,
  mergeJsonFile,
} from '@/harness/templates'
import { resolveTargetsAsync, pruneForeignHarnessFiles } from '@/harness/detect-target'
import { enrichDomainProfile } from '@/harness/profile'
import { harnessReadmeContent } from '@/harness/harness-readme'
import {
  BootstrapFileResult,
  BootstrapHarnessResult,
  DomainProfile,
  HarnessTarget,
} from '@/harness/types'
import { HarnessInterviewAnswers, runHarnessInterview } from '@/harness/bootstrap-interview'
import { renderLanguageRulesSection } from '@/harness/language-rules'
import { detectLanguages } from '@/harness/detect-language'

export interface BootstrapHarnessOptions {
  projectRoot?: string
  targets?: HarnessTarget[]
  profile?: Partial<DomainProfile>
  force?: boolean
  save_profile?: boolean
  /** Delete harness artifacts for other AI tools (keeps active target only) */
  prune_foreign?: boolean
  dry_run_prune?: boolean
  /**
   * Pre-rendered markdown block of per-language coding rules. When provided,
   * injected into AGENTS.md / CLAUDE.md / Cursor MDC / Windsurf / Continue rules.
   * Generated by runHarnessInterview() or renderLanguageRulesSection().
   */
  language_rules_section?: string
  /**
   * Optional interview answers. When `interview:true` or interview answers
   * are provided but no `language_rules_section`, the wizard runs automatically
   * (nonInteractive: true by default unless `interactive:true`).
   */
  interview_answers?: HarnessInterviewAnswers
  /** Run the interview in interactive mode — return pending state to the caller */
  interview?: boolean
}

async function writeFile(
  abs: string,
  content: string,
  force: boolean,
  target: HarnessTarget | 'shared'
): Promise<BootstrapFileResult> {
  try {
    await fs.access(abs)
    if (!force) return { path: abs, action: 'skipped', target }
  } catch {
    /* create */
  }
  await fs.mkdir(path.dirname(abs), { recursive: true })
  await fs.writeFile(abs, content, 'utf-8')
  let action: BootstrapFileResult['action'] = 'created'
  try {
    await fs.access(abs)
    action = force ? 'updated' : 'created'
  } catch {
    action = 'created'
  }
  return { path: abs, action, target }
}

export async function bootstrapHarness(
  vault: ObsidianVault,
  opts: BootstrapHarnessOptions = {}
): Promise<BootstrapHarnessResult> {
  const projectRoot = path.resolve(opts.projectRoot || resolveProjectRoot())
  const { targets, detection } = await resolveTargetsAsync(opts.targets, projectRoot)
  const force = opts.force === true
  const files: BootstrapFileResult[] = []

  let { profile } = await loadDomainProfile(vault, projectRoot)
  if (opts.profile) {
    profile = {
      ...profile,
      ...opts.profile,
      stack: { ...profile.stack, ...opts.profile.stack },
      wiki: { ...profile.wiki, ...opts.profile.wiki },
      loop: { ...profile.loop, ...opts.profile.loop },
      harness: { ...profile.harness, ...opts.profile.harness },
    }
  }
  profile = await enrichDomainProfile(vault, profile, projectRoot)
  if (!profile.wiki?.overview_pages?.length) {
    profile.wiki = {
      ...profile.wiki,
      overview_pages: await inferOverviewPagesFromWiki(vault),
    }
  }

  // ── Language rules section ───────────────────────────────────────────────
  // Resolution order:
  //   1. opts.language_rules_section (caller pre-rendered)
  //   2. opts.interview_answers provided → render from those answers
  //   3. opts.interview === true (interactive) → return pending state (no files)
  //   4. none of the above → auto-detect languages and render non-interactively
  let languageRulesSection = opts.language_rules_section
  let interviewPayload: {
    status: string
    question?: unknown
    detected_languages?: unknown
    answers?: HarnessInterviewAnswers
  } | null = null

  if (opts.interview && !languageRulesSection) {
    // Interactive mode: surface the next pending question to the caller.
    const interview = await runHarnessInterview({
      projectRoot,
      answers: opts.interview_answers,
      stackHints: profile.stack,
      nonInteractive: false,
    })
    interviewPayload = interview
    if (interview.status === 'pending') {
      // No files are written yet — let the caller collect answers first.
      return {
        ok: false,
        project_root: projectRoot,
        vault_root: vault.rootPath,
        targets,
        target_detection: {
          target: detection.target,
          source: detection.source,
          hint: detection.hint,
        },
        files: [],
        profile_path: profilePathFn(projectRoot),
        next_steps: [],
        interview,
      }
    }
    if (interview.status === 'complete' && interview.rendered_rules_section) {
      languageRulesSection = interview.rendered_rules_section
      if (interview.answers?.notes) {
        profile.description = profile.description
          ? `${profile.description} — ${interview.answers.notes}`
          : interview.answers.notes
      }
    }
  }

  if (!languageRulesSection && opts.interview_answers) {
    // Answers provided but no pre-rendered block — render from answers
    const interview = await runHarnessInterview({
      projectRoot,
      answers: opts.interview_answers,
      stackHints: profile.stack,
      nonInteractive: true,
    })
    if (interview.status === 'complete' && interview.rendered_rules_section) {
      languageRulesSection = interview.rendered_rules_section
    }
  }

  if (!languageRulesSection) {
    // Fully auto-detect and render without surfacing any questions
    const detection = await detectLanguages(projectRoot)
    const langs = detection.languages.map((d) => d.id)
    if (langs.length) {
      languageRulesSection = renderLanguageRulesSection(langs, { strictness: 'standard' })
    }
  }

  const ruleExtras = languageRulesSection
    ? { language_rules_section: languageRulesSection }
    : undefined

  let profilePath = ''
  if (opts.save_profile !== false) {
    profilePath = await saveDomainProfile(profile, projectRoot)
    files.push({ path: profilePath, action: 'updated', target: 'shared' })
  }

  // Shared AGENTS.md
  const agentsPath = path.join(projectRoot, 'AGENTS.md')
  const agentsResult = await writeFile(
    agentsPath,
    projectAgentsMd(profile, ruleExtras),
    force,
    'shared'
  )
  files.push({ ...agentsResult, target: 'shared' })

  const posixRoot = projectRoot.replace(/\\/g, '/')

  if (targets.includes('cursor')) {
    files.push(
      await writeFile(
        path.join(projectRoot, '.cursor', 'rules', 'aio-domain-harness.mdc'),
        cursorRuleMdc(profile, ruleExtras),
        force,
        'cursor'
      )
    )
    const hooksDir = path.join(projectRoot, '.cursor', 'hooks')
    await fs.mkdir(hooksDir, { recursive: true })
    files.push(
      await writeFile(
        path.join(projectRoot, '.cursor', 'hooks.json'),
        cursorHooksJson(),
        force,
        'cursor'
      )
    )
    files.push(
      await writeFile(
        path.join(hooksDir, 'aio-session-start.mjs'),
        cursorSessionStartHook(),
        force,
        'cursor'
      )
    )
    files.push(
      await writeFile(
        path.join(hooksDir, 'aio-before-prompt.mjs'),
        cursorBeforePromptHook(),
        force,
        'cursor'
      )
    )
    const mcpPath = path.join(projectRoot, '.cursor', 'mcp.json')
    const mcpAction = await mergeJsonFile(
      mcpPath,
      JSON.parse(mcpJsonCursor(posixRoot)) as Record<string, unknown>,
      'mcpServers'
    )
    files.push({ path: mcpPath, action: mcpAction, target: 'cursor' })
  }

  if (targets.includes('claude')) {
    files.push(
      await writeFile(
        path.join(projectRoot, 'CLAUDE.md'),
        claudeMd(profile, ruleExtras),
        force,
        'claude'
      )
    )
    const claudeHooksDir = path.join(projectRoot, '.claude', 'hooks')
    await fs.mkdir(claudeHooksDir, { recursive: true })
    files.push(
      await writeFile(
        path.join(projectRoot, '.claude', 'settings.json'),
        claudeSettingsJson(),
        force,
        'claude'
      )
    )
    files.push(
      await writeFile(
        path.join(claudeHooksDir, 'aio-session-start.mjs'),
        claudeSessionStartHook(),
        force,
        'claude'
      )
    )
    files.push(
      await writeFile(
        path.join(claudeHooksDir, 'aio-before-prompt.mjs'),
        claudeBeforePromptHook(),
        force,
        'claude'
      )
    )
    const mcpPath = path.join(projectRoot, '.mcp.json')
    const mcpAction = await mergeJsonFile(
      mcpPath,
      JSON.parse(mcpJsonClaude(posixRoot)) as Record<string, unknown>,
      'mcpServers'
    )
    files.push({ path: mcpPath, action: mcpAction, target: 'claude' })
  }

  if (targets.includes('opencode')) {
    const ocPath = path.join(projectRoot, 'opencode.json')
    const ocAction = await mergeJsonFile(
      ocPath,
      JSON.parse(opencodeJson(posixRoot)) as Record<string, unknown>,
      'mcp'
    )
    files.push({ path: ocPath, action: ocAction, target: 'opencode' })
    try {
      const raw = await fs.readFile(ocPath, 'utf-8')
      const existing = JSON.parse(raw) as Record<string, unknown>
      const instructions = existing.instructions as string[] | undefined
      if (!instructions?.includes('AGENTS.md')) {
        existing.instructions = [...(instructions || []), 'AGENTS.md']
        await fs.writeFile(ocPath, JSON.stringify(existing, null, 2), 'utf-8')
      }
    } catch {
      /* mergeJsonFile created file with instructions already */
    }
    files.push(
      await writeFile(
        path.join(projectRoot, '.opencode', 'plugins', 'aio-harness.mjs'),
        opencodeHarnessPlugin(),
        force,
        'opencode'
      )
    )
  }

  if (targets.includes('codex')) {
    const codexHooksDir = path.join(projectRoot, '.codex', 'hooks')
    await fs.mkdir(codexHooksDir, { recursive: true })
    files.push(
      await writeFile(
        path.join(projectRoot, '.codex', 'mcp.toml'),
        codexToml(posixRoot),
        force,
        'codex'
      )
    )
    files.push(
      await writeFile(
        path.join(projectRoot, '.codex', 'hooks.json'),
        codexHooksJson(),
        force,
        'codex'
      )
    )
    files.push(
      await writeFile(
        path.join(codexHooksDir, 'aio-session-start.mjs'),
        claudeSessionStartHook(),
        force,
        'codex'
      )
    )
    files.push(
      await writeFile(
        path.join(codexHooksDir, 'aio-before-prompt.mjs'),
        claudeBeforePromptHook(),
        force,
        'codex'
      )
    )
    // AGENTS.md is written once above (shared); do not force-overwrite here.
  }

  if (targets.includes('windsurf')) {
    const wsHooksDir = path.join(projectRoot, '.windsurf', 'hooks')
    await fs.mkdir(wsHooksDir, { recursive: true })
    files.push(
      await writeFile(
        path.join(projectRoot, '.windsurf', 'rules', 'aio-domain-harness.md'),
        windsurfRuleMd(profile, ruleExtras),
        force,
        'windsurf'
      )
    )
    files.push(
      await writeFile(
        path.join(projectRoot, '.windsurf', 'hooks.json'),
        windsurfHooksJson(),
        force,
        'windsurf'
      )
    )
    files.push(
      await writeFile(
        path.join(wsHooksDir, 'aio-before-prompt.mjs'),
        windsurfBeforePromptHook(),
        force,
        'windsurf'
      )
    )
    files.push(
      await writeFile(
        path.join(projectRoot, '.windsurf', 'mcp_config.json'),
        windsurfMcpJson(posixRoot),
        force,
        'windsurf'
      )
    )
  }

  if (targets.includes('continue')) {
    const contHooksDir = path.join(projectRoot, '.continue', 'hooks')
    await fs.mkdir(contHooksDir, { recursive: true })
    files.push(
      await writeFile(
        path.join(projectRoot, '.continue', 'rules', 'aio-domain-harness.md'),
        continueRuleMd(profile, ruleExtras),
        force,
        'continue'
      )
    )
    files.push(
      await writeFile(
        path.join(projectRoot, '.continue', 'settings.json'),
        continueSettingsJson(),
        force,
        'continue'
      )
    )
    files.push(
      await writeFile(
        path.join(contHooksDir, 'aio-session-start.mjs'),
        claudeSessionStartHook(),
        force,
        'continue'
      )
    )
    files.push(
      await writeFile(
        path.join(contHooksDir, 'aio-before-prompt.mjs'),
        claudeBeforePromptHook(),
        force,
        'continue'
      )
    )
    files.push(
      await writeFile(
        path.join(projectRoot, '.continue', 'aio-mcp.yaml'),
        continueMcpYaml(posixRoot),
        force,
        'continue'
      )
    )
  }

  // Harness readme snippet
  const readmeSnippet = path.join(projectRoot, '.aio', 'HARNESS.md')
  files.push(await writeFile(readmeSnippet, harnessReadmeContent(targets), force, 'shared'))

  if (opts.prune_foreign) {
    const active = detection as { target?: HarnessTarget } & typeof detection
    const activeTarget = (active.target || 'cursor') as Exclude<HarnessTarget, 'all'>
    const pruned = await pruneForeignHarnessFiles(projectRoot, activeTarget, {
      dry_run: opts.dry_run_prune === true,
    })
    for (const p of pruned) {
      files.push({
        path: path.join(projectRoot, p.rel),
        action: p.action === 'deleted' ? 'updated' : 'skipped',
        target: p.target,
      })
    }
  }

  await fs.mkdir(path.join(projectRoot, '.aio'), { recursive: true })

  // Persist language rules snapshot for re-runs without re-detection
  if (languageRulesSection) {
    const rulesPath = path.join(projectRoot, '.aio', 'language-rules.md')
    await fs.writeFile(rulesPath, languageRulesSection, 'utf-8')
    files.push({ path: rulesPath, action: 'updated', target: 'shared' })
  }

  const result = {
    ok: true,
    project_root: projectRoot,
    vault_root: vault.rootPath,
    targets,
    target_detection: {
      target: detection.target,
      source: detection.source,
      hint: detection.hint,
    },
    files,
    profile_path: profilePath,
    next_steps: [
      'Restart MCP in your AI client (Cursor: reload MCP; Claude/Codex: restart session)',
      'Codex: trust project + review hooks via /hooks',
      'OpenCode: restart after .opencode/plugins/ is created',
      'For Cursor/Claude/Codex/Continue CLI: ensure hooks are enabled',
      "Natural language (KO/EN): say '하네스 구성해줘' or 'bootstrap harness' (auto-detects your AI tool; use targets:['all'] for every client)",
      'Call seed_stack_playbooks once to populate vault/wiki/stacks/',
      'Call bootstrap_domain({ task: "your feature" }) before coding',
      'Edit .aio/domain-profile.yaml for stack/domain tweaks; re-run bootstrap_harness',
      'To re-interview language rules: call bootstrap_harness with interview:true then merge answers',
    ],
    interview: interviewPayload || undefined,
  } as BootstrapHarnessResult

  return result
}

export async function readDomainProfileYaml(projectRoot?: string): Promise<DomainProfile | null> {
  try {
    const raw = await fs.readFile(
      path.join(projectRoot || resolveProjectRoot(), '.aio', 'domain-profile.yaml'),
      'utf-8'
    )
    return yaml.load(raw) as DomainProfile
  } catch {
    return null
  }
}
