export function harnessReadmeContent(targets: string[]): string {
  return [
    '# aio-mcp Domain Harness',
    '',
    `Generated: ${new Date().toISOString()}`,
    `Targets: ${targets.join(', ')}`,
    '',
    '## Quick start',
    '',
    '1. MCP connected with `AIO_PROJECT_ROOT` = this project',
    '2. Say **하네스 구성해줘** / **bootstrap harness** or **아키텍처 설계해줘** / **design the architecture** (or `aio_prompt` with execute:true)',
    '3. `seed_stack_playbooks` once for stack wiki under vault/wiki/stacks/',
    '4. `bootstrap_domain` with your task',
    '5. `run_domain_loop` for full agent brief',
    '',
    'Profile: `.aio/domain-profile.yaml`',
    'Cached context: `.aio/harness-context.json`',
    '',
    '## Wiki taxonomy (recommended)',
    '',
    '```',
    'vault/wiki/',
    '  domain/        # bounded context pages',
    '  architecture/  # ADR, saga, principles',
    '  engineering/   # coding rules, testing, security',
    '  stacks/        # seed_stack_playbooks',
    '```',
    '',
    '## Prompt cookbook (copy-paste)',
    '',
    '### Ingest pipeline (raw + wiki + lint)',
    '',
    '```',
    '# KO',
    'ingest pipeline: docs/policy.md 를 raw 저장하고',
    '개념 wiki ingest — 결제 Payment, 환불 Returns',
    '끝나면 wiki lint deep',
    '',
    '# EN',
    'run ingest pipeline for docs/policy.md then lint the wiki',
    '```',
    '',
    '### Raw only',
    '',
    '```',
    '# KO: raw ingest 제목: PG 정책 원본 / 파일: docs/pg-policy.md',
    '# EN: ingest raw title: PG policy source / file: docs/pg-policy.md',
    '```',
    '',
    '### Wiki search + implement',
    '',
    '```',
    '# KO: bootstrap_domain: 장바구니 API → wiki 검색 장바구니 → plan task',
    '# EN: bootstrap domain cart API → search the wiki for cart → plan task',
    '```',
    '',
    '### Architecture + stacks',
    '',
    '```',
    'seed_stack_playbooks Spring Boot React',
    '# KO: design_architecture 결제 마이크로서비스 분리',
    '# EN: design the architecture for payment microservices',
    '```',
    '',
    '### Session DAG recipe',
    '',
    '```',
    'plan task 결제 API — success: tests pass',
    'execute_dag (independent tasks only)',
    'collect_results',
    '```',
    '',
    '### Harness maintenance',
    '',
    '```',
    'aio bootstrap-harness --prune-foreign',
    'aio doctor --fail',
    '```',
    '',
  ].join('\n')
}
