import * as fs from "fs/promises";
import * as path from "path";
import { DomainProfile, HarnessTarget } from "@/harness/types";

export function projectAgentsMd(profile: DomainProfile): string {
  const stack = [
    profile.stack?.backend && `Backend: ${profile.stack.backend}`,
    profile.stack?.frontend && `Frontend: ${profile.stack.frontend}`,
    profile.stack?.infra && `Infra: ${profile.stack.infra}`,
  ]
    .filter(Boolean)
    .join(" · ");

  return `# Project Agent Harness (aio-mcp)

> Auto-generated by \`bootstrap_harness\`. Domain: **${profile.domain}** — ${profile.description}

## Before any implementation

1. Call MCP **\`bootstrap_domain\`** with the user's task (or **\`run_domain_loop\`** for full loop brief).
2. Read returned wiki pages and **cite** \`[[page-title]]\` in your plan.
3. Call **\`plan_task\`** for multi-step work; **\`execute_dag\`** when tasks are independent.
4. After durable decisions, **\`file_back\`** into the wiki.
5. Run **\`lint_wiki\`** when wiki structure may have changed.

## Hard rules

- Do **not** invent domain facts missing from wiki/raw.
- Respect **bounded contexts** from wiki (do not merge unrelated domains in one module).
- ${profile.loop?.require_citations !== false ? "Answers must include wiki citations." : "Prefer wiki citations."}
${stack ? `\n## Stack\n\n${stack}\n` : ""}
## MCP tools (priority)

${(profile.harness?.suggested_mcp_tools || [])
  .map((t) => `- \`${t}\``)
  .join("\n")}

## Loop

${(profile.loop?.steps || [])
  .map((s, i) => `${i + 1}. ${s}`)
  .join("\n")}

Re-run \`bootstrap_harness\` after changing \`.aio/domain-profile.yaml\`.
`;
}

export function cursorRuleMdc(profile: DomainProfile): string {
  return `---
description: aio-mcp domain wiki harness — always bootstrap wiki context before coding
alwaysApply: true
---

# Domain Wiki Harness (aio-mcp)

You work on **${profile.domain}**. ${profile.description}

## Mandatory workflow

1. **First tool call** for implementation tasks: \`bootstrap_domain\` with the user task (or \`run_domain_loop\`).
2. Use wiki citations from the context pack. Bounded contexts in wiki are authoritative.
3. Multi-step features: \`plan_task\` → \`execute_dag\` (use \`resume: true\` on retry).
4. End with \`file_back\` for durable architecture decisions.

## Never

- Skip wiki lookup and guess domain rules
- Collapse bounded contexts into one god-module
- Edit \`vault/raw/\` (immutable)

Stack: ${profile.stack?.backend || "—"} / ${profile.stack?.frontend || "—"}
`;
}

export function claudeMd(profile: DomainProfile): string {
  return projectAgentsMd(profile).replace(
    "# Project Agent Harness",
    "# Claude Code — Project Harness"
  );
}

export function cursorHooksJson(): string {
  return JSON.stringify(
    {
      version: 1,
      hooks: {
        sessionStart: [{ command: "node .cursor/hooks/aio-session-start.mjs" }],
        beforeSubmitPrompt: [
          {
            command: "node .cursor/hooks/aio-before-prompt.mjs",
            matcher: "UserPromptSubmit",
          },
        ],
      },
    },
    null,
    2
  );
}

export function cursorSessionStartHook(): string {
  return `#!/usr/bin/env node
/**
 * aio-mcp sessionStart — inject cached domain context from .aio/harness-context.json
 */
import fs from "fs";
import path from "path";

const root = process.cwd();
const cache = path.join(root, ".aio", "harness-context.json");
const profilePath = path.join(root, ".aio", "domain-profile.yaml");

let additional = "## aio-mcp harness\\n\\n";
additional += "Before coding, call MCP bootstrap_domain or run_domain_loop for the user task.\\n";
additional += "Follow AGENTS.md and vault wiki bounded contexts.\\n";

try {
  if (fs.existsSync(cache)) {
    const pack = JSON.parse(fs.readFileSync(cache, "utf8"));
    additional += "\\n### Cached domain context\\n";
    additional += "Task: " + (pack.task || "(none)") + "\\n";
    if (pack.pages?.length) {
      additional += "Wiki pages: " + pack.pages.map((p) => p.title).join(", ") + "\\n";
    }
    if (pack.harness_prompt) {
      additional += "\\n" + pack.harness_prompt.slice(0, 2000);
    }
  }
} catch {
  /* ignore */
}

try {
  if (fs.existsSync(profilePath)) {
    additional += "\\n(domain-profile.yaml present at .aio/)";
  }
} catch {
  /* ignore */
}

console.log(JSON.stringify({ additional_context: additional }));
`;
}

export function cursorBeforePromptHook(): string {
  return `#!/usr/bin/env node
/**
 * aio-mcp beforeSubmitPrompt — remind agent to bootstrap wiki for implementation-like prompts
 */
import fs from "fs";

let input = "";
process.stdin.setEncoding("utf8");
for await (const chunk of process.stdin) input += chunk;

let prompt = "";
try {
  const data = JSON.parse(input || "{}");
  prompt = data.prompt || data.text || "";
} catch {
  prompt = input;
}

const impl = /\\b(구현|만들|작성|추가|리팩|refactor|implement|create|build|fix|api|spring|react)\\b/i;
const cacheExists = fs.existsSync(".aio/harness-context.json");

if (impl.test(prompt) && !cacheExists) {
  console.log(
    JSON.stringify({
      additional_context:
        "aio-mcp: Call bootstrap_domain (or run_domain_loop) BEFORE writing code. Load wiki context for this task.",
    })
  );
} else {
  console.log("{}");
}
`;
}

export function mcpJsonCursor(projectRoot: string): string {
  return JSON.stringify(
    {
      mcpServers: {
        "aio-mcp": {
          command: "npx",
          args: ["-y", "@mindol1004/aio-mcp", "mcp-serve"],
          env: {
            AIO_PROJECT_ROOT: projectRoot,
          },
        },
      },
    },
    null,
    2
  );
}

export function mcpJsonClaude(projectRoot: string): string {
  return JSON.stringify(
    {
      mcpServers: {
        "aio-mcp": {
          type: "stdio",
          command: "npx",
          args: ["-y", "@mindol1004/aio-mcp", "mcp-serve"],
          env: {
            AIO_PROJECT_ROOT: projectRoot,
          },
        },
      },
    },
    null,
    2
  );
}

export function opencodeJson(projectRoot: string): string {
  return JSON.stringify(
    {
      $schema: "https://opencode.ai/config.json",
      mcp: {
        "aio-mcp": {
          type: "local",
          command: ["npx", "-y", "@mindol1004/aio-mcp", "mcp-serve"],
          enabled: true,
          environment: {
            AIO_PROJECT_ROOT: projectRoot,
          },
        },
      },
    },
    null,
    2
  );
}

export function codexToml(projectRoot: string): string {
  return `# aio-mcp — Codex CLI MCP (TOML format varies by version; adjust if needed)
[mcp_servers.aio-mcp]
command = "npx"
args = ["-y", "@mindol1004/aio-mcp", "mcp-serve"]

[mcp_servers.aio-mcp.env]
AIO_PROJECT_ROOT = "${projectRoot.replace(/\\/g, "/")}"
`;
}

export function windsurfMcpJson(projectRoot: string): string {
  return mcpJsonCursor(projectRoot);
}

export function continueMcpYaml(projectRoot: string): string {
  return `# Continue.dev — add to config.json mcpServers or use as reference
mcpServers:
  aio-mcp:
    command: npx
    args:
      - -y
      - "@mindol1004/aio-mcp"
      - mcp-serve
    env:
      AIO_PROJECT_ROOT: ${JSON.stringify(projectRoot)}
`;
}

export async function mergeJsonFile(
  filePath: string,
  merge: Record<string, unknown>,
  key: string
): Promise<"created" | "updated"> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  let existing: Record<string, unknown> = {};
  try {
    const raw = await fs.readFile(filePath, "utf-8");
    existing = JSON.parse(raw) as Record<string, unknown>;
  } catch {
    await fs.writeFile(filePath, JSON.stringify(merge, null, 2), "utf-8");
    return "created";
  }
  const bucket = (existing[key] as Record<string, unknown>) || {};
  const incoming = (merge[key] as Record<string, unknown>) || {};
  existing[key] = { ...bucket, ...incoming };
  await fs.writeFile(filePath, JSON.stringify(existing, null, 2), "utf-8");
  return "updated";
}

export function resolveTargets(targets?: HarnessTarget[]): HarnessTarget[] {
  if (!targets?.length || targets.includes("all")) {
    return ["cursor", "claude", "opencode", "codex", "windsurf", "continue"];
  }
  return targets;
}
