/** Keyword registry — every MCP tool routable via substring / pattern scoring (KO + EN). */

export interface ToolKeywordDef {
  id: string
  category: 'harness' | 'wiki' | 'session' | 'dag' | 'ops' | 'branch' | 'knowledge'
  keywords: string[]
  /** Extra regex bonus (source stored for hook codegen) */
  patterns?: RegExp[]
  weight?: number
  /** Minimum score to match (default 3) */
  minScore?: number
  hint: string
  /** Primary string param name when executing from free text */
  textParam?:
    | 'query'
    | 'task'
    | 'title'
    | 'intent'
    | 'message'
    | 'action'
    | 'topic'
    | 'change_description'
    | 'content'
}

export const TOOL_KEYWORDS: ToolKeywordDef[] = [
  // ── Harness ──
  {
    id: 'brainstorm_design',
    category: 'harness',
    keywords: [
      '브레인스토밍',
      'brainstorm',
      '기획',
      '요구사항',
      '와이어프레임',
      '프로토타입',
      '설계 추천',
      'trade-off',
      'tradeoff',
      'db 설계',
      'database design',
      '알고리즘',
      '구현 방식',
      '테스트 전략',
      'test strategy',
      '어떤 방식',
      'help me design',
      'design options',
      'product planning',
      '요구사항 정리',
      'trade-offs',
    ],
    patterns: [
      /브레인\s*스토밍/i,
      /기획\s*(도움|추천|검토)/i,
      /\b(ux|ui)\b\s*(설계|검토|추천|design|review)/i,
      /디자인\s*(방향|추천|시스템)/i,
      /설계\s*(추천|제안|조언)/i,
      /어떤\s*(방식|알고리즘|패턴)/i,
      /\bprd\b/i,
      /help\s+me\s+(design|plan|brainstorm)/i,
      /what\s+(approach|options?|trade-?offs?)/i,
      /보안\s*(검토|설계|전략)/i,
      /security\s*(review|design|strategy)/i,
      /요구사항\s*(정리|도출|분석)/i,
      /테스트\s*전략\s*(짜|만들|세워)/i,
      /trade-?offs?\s+for/i,
    ],
    weight: 2,
    minScore: 4,
    textParam: 'topic',
    hint: 'Full-lifecycle brainstorm: planning, UX, design, domain, DB, security, testing, DevOps…',
  },
  {
    id: 'bootstrap_harness',
    category: 'harness',
    keywords: [
      'agents.md',
      'cursor rule',
      'cursor hooks',
      'hook 설정',
      'mcp 설정',
      'bootstrap_harness',
      'bootstrap harness',
      'setup harness',
      '하네스 구성',
      '하네스 설정',
      '에이전트 규칙',
      'agent rules',
      'generate agents.md',
    ],
    patterns: [
      /하네스\s*(구성|설정|셋업|만들|생성|적용)/i,
      /harness\s*(setup|bootstrap|configure|init)/i,
      /bootstrap\s+(the\s+)?harness/i,
      /set\s*up\s+(the\s+)?harness/i,
      /에이전트\s*규칙/i,
      /(generate|create|setup)\s+agents\.md/i,
      /cursor\s+hooks?\s*(setup|config|설정)/i,
    ],
    weight: 2,
    minScore: 6,
    textParam: 'message',
    hint: 'Generate AGENTS.md, Cursor rules/hooks, MCP configs',
  },
  {
    id: 'design_architecture',
    category: 'harness',
    keywords: [
      '아키텍처',
      'architecture',
      '모듈 구조',
      'bounded context',
      '스택 구성',
      'design_architecture',
      'architecture design',
      '시스템 설계',
      'system architecture',
    ],
    patterns: [
      /아키텍처\s*(구성|설계|만들|생성|짜|정의)/i,
      /architecture\s*(design|setup|create)/i,
      /design\s+(the\s+|system\s+)?architecture/i,
      /시스템\s*설계/i,
      /모듈\s*구조\s*(잡|짜|설계)/i,
    ],
    weight: 2,
    textParam: 'intent',
    hint: 'Wiki + stack based architecture design',
  },
  {
    id: 'seed_stack_playbooks',
    category: 'harness',
    keywords: [
      '스택 플레이북',
      'stack playbook',
      'playbook 시드',
      'seed_stack',
      'seed stacks',
      '베스트 프랙티스 wiki',
      '플레이북 시드',
      'seed playbooks',
    ],
    patterns: [
      /스택\s*플레이북\s*(시드|넣|추가|생성)/i,
      /플레이북\s*(시드|넣|추가|생성)/i,
      /seed\s+(the\s+)?(stack\s+)?playbooks?/i,
    ],
    weight: 2,
    hint: 'Seed vault/wiki/stacks/* playbooks',
  },
  {
    id: 'generate_usage_guide',
    category: 'harness',
    keywords: [
      '도구 사용법',
      '툴 사용법',
      '사용 가이드',
      '매뉴얼',
      'tool guide',
      'usage guide',
      '사용 설명서',
      'documentation',
      'how to use',
      '튜토리얼',
      'tutorial',
      'mcp 도구',
      'mcp tools',
      'tool documentation',
      '레퍼런스',
      'reference',
    ],
    patterns: [
      /도구\s*사용\s*(법|가이드|설명|메뉴얼)/i,
      /툴\s*사용\s*(법|가이드)/i,
      /사용\s*(가이드|설명서|메뉴얼)/i,
      /tool\s*(guide|usage|documentation|reference)/i,
      /how\s+to\s+use/i,
      /usage\s+guide/i,
      /generate\s+(tool|mcp)\s*doc/i,
      /documentation\s+(guide|manual)/i,
    ],
    weight: 2,
    hint: 'Generate MCP tool usage guide in docs/mcp-guide/',
  },
  {
    id: 'run_domain_loop',
    category: 'harness',
    keywords: [
      '도메인 루프',
      'domain loop',
      'run_domain_loop',
      'wiki 기반 개발',
      'wiki 컨텍스트 구현',
      'run domain loop',
    ],
    patterns: [/run\s+(the\s+)?domain\s+loop/i, /도메인\s*루프/i],
    weight: 1,
    textParam: 'task',
    hint: 'Full domain loop brief',
  },
  {
    id: 'domain_context',
    category: 'harness',
    keywords: [
      'domain_context',
      'domain context',
      'wiki context',
      'context pack',
      '도메인 컨텍스트',
      'wiki 컨텍스트',
    ],
    patterns: [/domain\s+context/i, /wiki\s*컨텍스트/i, /도메인\s*컨텍스트/i],
    weight: 2,
    minScore: 4,
    textParam: 'task',
    hint: 'Unified domain context (prefer over bootstrap_domain)',
  },
  {
    id: 'bootstrap_domain',
    category: 'harness',
    keywords: [
      '도메인 컨텍스트',
      'bootstrap_domain',
      'wiki 컨텍스트',
      '컨텍스트 팩',
      'harness-context',
      'domain context',
      'bootstrap domain',
      'context pack',
    ],
    patterns: [
      /wiki\s*컨텍스트/i,
      /도메인\s*컨텍스트/i,
      /bootstrap\s+(the\s+)?domain/i,
      /domain\s+context\s*(pack)?/i,
    ],
    weight: 1,
    minScore: 4,
    textParam: 'task',
    hint: 'Build domain context pack from wiki',
  },
  {
    id: 'get_domain_profile',
    category: 'harness',
    keywords: [
      'get_domain_profile',
      '프로필 읽',
      'read domain profile',
      'get domain profile',
      '도메인 프로필 읽',
      'show domain profile',
    ],
    patterns: [
      /(read|get|show|load)\s+(the\s+)?domain\s+profile/i,
      /도메인\s*프로필\s*(읽|조회|보여)/i,
      /프로필\s*읽/i,
    ],
    minScore: 4,
    hint: 'Read .aio/domain-profile.yaml',
  },
  {
    id: 'save_domain_profile',
    category: 'harness',
    keywords: [
      '프로필 저장',
      'save profile',
      'save_domain_profile',
      '도메인 프로필 저장',
      'save domain profile',
    ],
    patterns: [/save\s+(the\s+)?domain\s+profile/i, /도메인\s*프로필\s*저장/i, /프로필\s*저장/i],
    minScore: 4,
    weight: 2,
    hint: 'Save domain profile',
  },
  {
    id: 'list_stack_playbooks',
    category: 'harness',
    keywords: [
      '스택 목록',
      'list stack',
      'list_stack',
      '플레이북 목록',
      'stack list',
      'list playbooks',
      'list stack playbooks',
      'list the stacks',
      'show stacks',
    ],
    patterns: [/list\s+(the\s+)?(stack\s+)?playbooks?/i, /list\s+(the\s+)?stacks/i, /스택\s*목록/i],
    minScore: 4,
    hint: 'List available stack playbook ids',
  },

  // ── Wiki ──
  {
    id: 'query_wiki',
    category: 'wiki',
    keywords: [
      'wiki 검색',
      'wiki 조회',
      'wiki search',
      'wiki query',
      'query wiki',
      'query_wiki',
      '위키 검색',
      '위키에서',
      'wiki에서',
      '도메인 wiki',
      'wiki 찾',
      'search wiki',
      'look up wiki',
      'find in the wiki',
      'ask the wiki',
    ],
    patterns: [
      /wiki.*(검색|조회|찾|search|query)/i,
      /위키.*(검색|조회|찾)/i,
      /(search|query|look\s*up|find)\s+(in\s+|the\s+|our\s+)?wiki/i,
      /search\s+the\s+wiki/i,
      /find\s+in\s+(the\s+)?wiki/i,
      /ask\s+(the\s+)?wiki/i,
    ],
    weight: 1,
    textParam: 'query',
    hint: 'Semantic wiki search with citations',
  },
  {
    id: 'lint_wiki',
    category: 'wiki',
    keywords: [
      'wiki lint',
      'lint_wiki',
      '위키 린트',
      'wiki 검사',
      'wiki health',
      'broken link',
      '위키 점검',
      'lint wiki',
      '위키 건강',
      'check wiki health',
    ],
    patterns: [
      /wiki\s*lint/i,
      /lint\s+(the\s+)?wiki/i,
      /위키\s*(점검|검사|lint|건강)/i,
      /orphan\s+(wiki\s+)?pages?/i,
      /broken\s+links?/i,
      /check\s+(the\s+)?wiki\s*health/i,
    ],
    weight: 2,
    hint: 'Wiki structure health check',
  },
  {
    id: 'get_wiki_schema',
    category: 'wiki',
    keywords: [
      'wiki schema',
      'get_wiki_schema',
      '위키 스키마',
      'wiki 규칙',
      'AGENTS.md schema',
      'read wiki schema',
    ],
    patterns: [/read\s+(the\s+)?wiki\s*schema/i, /위키\s*스키마/i, /get\s+wiki\s*schema/i],
    minScore: 5,
    hint: 'Read vault wiki schema',
  },
  {
    id: 'ingest_raw',
    category: 'wiki',
    keywords: [
      'raw ingest',
      'ingest_raw',
      '원본 저장',
      'raw 저장',
      '원문 ingest',
      'store raw',
      'ingest raw',
      'save to raw',
      'raw에 저장',
    ],
    patterns: [/save\s+to\s+raw/i, /raw에\s*저장/i, /store\s+(in\s+|to\s+)?raw/i],
    minScore: 5,
    textParam: 'title',
    hint: 'Store immutable original under vault/raw/',
  },
  {
    id: 'ingest_source',
    category: 'wiki',
    keywords: [
      'wiki ingest',
      'ingest_source',
      '위키 ingest',
      '개념 페이지',
      'wiki 페이지 생성',
      'wiki 추가',
      'ingest source',
      'create wiki page',
    ],
    minScore: 4,
    textParam: 'title',
    hint: 'Create/update one wiki concept page',
  },
  {
    id: 'ingest_source_batch',
    category: 'wiki',
    keywords: [
      'ingest_source_batch',
      'wiki batch',
      '개념 batch',
      '여러 개념',
      'wiki 일괄',
      'batch ingest',
      'ingest batch',
    ],
    patterns: [/wiki.*(batch|일괄|여러)/i, /개념.*(batch|여러|일괄)/i, /batch\s+ingest/i],
    minScore: 4,
    textParam: 'title',
    hint: 'Create multiple wiki concept pages from one raw source',
  },
  {
    id: 'ingest_pipeline',
    category: 'wiki',
    keywords: [
      'ingest pipeline',
      'ingest_pipeline',
      '문서 ingest',
      'raw wiki lint',
      'ingest 파이프라인',
      'run ingest',
      'ingest document',
      'ingest this document',
      '이 문서 인제스트',
    ],
    patterns: [
      /ingest\s*pipeline/i,
      /(raw|원본).*(wiki|위키).*(lint|ingest)/i,
      /run\s+(the\s+)?ingest(\s+pipeline)?/i,
      /ingest\s+(this\s+)?(document|file|doc)/i,
      /이\s*문서\s*인제스트/i,
      /문서\s*인제스트/i,
    ],
    minScore: 6,
    weight: 3,
    textParam: 'title',
    hint: 'raw → wiki concept(s) → lint. Needs file_path, raw_id, or substantial content — not chat text alone.',
  },
  {
    id: 'update_wiki_page',
    category: 'wiki',
    keywords: [
      'wiki 수정',
      'update_wiki',
      '위키 수정',
      'wiki 업데이트',
      '페이지 수정',
      'update wiki',
      'update wiki page',
      'edit wiki page',
    ],
    patterns: [
      /edit\s+(the\s+)?wiki\s*page/i,
      /update\s+(the\s+)?wiki\s*page/i,
      /(위키|wiki|페이지)\s*수정/i,
    ],
    minScore: 4,
    textParam: 'title',
    hint: 'Update existing wiki page',
  },
  {
    id: 'file_back',
    category: 'wiki',
    keywords: [
      'file_back',
      'wiki 반영',
      '위키 반영',
      'wiki 기록',
      '지식 저장 wiki',
      'wiki에 저장',
      'file back',
      'write back to wiki',
      'file to wiki',
    ],
    patterns: [
      /file\s+(this\s+)?back\s+to\s+(the\s+)?wiki/i,
      /write\s+back\s+to\s+(the\s+)?wiki/i,
      /wiki\s*(반영|기록)/i,
    ],
    weight: 1,
    textParam: 'title',
    hint: 'Write durable synthesis back to wiki',
  },
  {
    id: 'propose_wiki_change',
    category: 'wiki',
    keywords: [
      'propose_wiki',
      'wiki mr',
      'wiki 변경 제안',
      '위키 변경 제안',
      '위키 제안',
      'wiki diff 제안',
      'propose wiki change',
      'propose a wiki change',
    ],
    patterns: [
      /wiki\s*mr\b/i,
      /wiki\s+proposal(?!s)/i,
      /propose\s+(a\s+)?wiki\s+(change|mr|proposal)/i,
      /위키\s*(변경\s*)?제안/i,
      /wiki\s*변경\s*제안/i,
    ],
    minScore: 4,
    textParam: 'title',
    hint: 'Create wiki change proposal for review',
  },
  {
    id: 'list_wiki_proposals',
    category: 'wiki',
    keywords: [
      'wiki proposals',
      'list_wiki_proposals',
      '제안 목록',
      'pending wiki',
      'list wiki proposals',
      'show wiki proposals',
    ],
    patterns: [/wiki\s+proposals\b/i, /(list|show)\s+(wiki\s+)?proposals/i, /제안\s*목록/i],
    minScore: 4,
    weight: 2,
    hint: 'List wiki MR proposals',
  },
  {
    id: 'apply_wiki_proposal',
    category: 'wiki',
    keywords: [
      'apply wiki',
      'apply_wiki_proposal',
      'wiki merge',
      '제안 적용',
      'wiki 승인',
      'apply wiki proposal',
      'merge wiki proposal',
    ],
    patterns: [
      /apply\s+(the\s+)?wiki\s+proposal/i,
      /merge\s+(the\s+)?wiki\s+proposal/i,
      /제안\s*적용/i,
      /wiki\s*승인/i,
    ],
    minScore: 5,
    weight: 2,
    hint: 'Merge approved wiki proposal',
  },
  {
    id: 'reject_wiki_proposal',
    category: 'wiki',
    keywords: ['reject wiki', 'reject_wiki_proposal', '제안 거부', 'reject wiki proposal'],
    patterns: [/reject\s+(the\s+)?wiki\s+proposal/i, /제안\s*거부/i],
    minScore: 5,
    weight: 2,
    hint: 'Reject wiki proposal',
  },
  {
    id: 'wiki_diff',
    category: 'wiki',
    keywords: ['wiki diff', 'wiki_diff', '위키 diff', '변경 미리보기', 'preview wiki diff'],
    minScore: 4,
    textParam: 'title',
    hint: 'Preview wiki page diff',
  },
  {
    id: 'scan_raw_inbox',
    category: 'wiki',
    keywords: [
      'raw inbox',
      'scan_raw_inbox',
      'raw-inbox',
      '파일 드롭',
      'inbox ingest',
      '자동 ingest',
      'scan inbox',
      'scan raw inbox',
      'dropped files',
      'process dropped files',
    ],
    patterns: [
      /raw\s*inbox/i,
      /inbox\s*ingest/i,
      /scan\s+(the\s+)?(raw[-\s]?)?inbox/i,
      /process\s+(dropped\s+)?files/i,
      /dropped\s+files/i,
    ],
    minScore: 4,
    hint: 'Process vault/raw-inbox/ dropped files',
  },
  {
    id: 'list_vaults',
    category: 'wiki',
    keywords: [
      'list vaults',
      'list_vaults',
      'vault 목록',
      'multi vault',
      '멀티 vault',
      'vault list',
      '멀티 볼트',
      'registered vaults',
      'show vaults',
    ],
    patterns: [/(list|show)\s+(registered\s+)?vaults/i, /(멀티\s*)?(볼트|vault)\s*목록/i],
    minScore: 4,
    hint: 'List registered vaults',
  },
  {
    id: 'register_vault',
    category: 'wiki',
    keywords: [
      'register vault',
      'register_vault',
      'vault 등록',
      'vault 추가',
      'add vault',
      '볼트 등록',
    ],
    patterns: [/register\s+(a\s+|the\s+)?vault/i, /(볼트|vault)\s*(등록|추가)/i],
    minScore: 5,
    hint: 'Register vault in vaults.yaml',
  },
  {
    id: 'get_dashboard_stats',
    category: 'ops',
    keywords: [
      'get_dashboard_stats',
      '대시보드',
      'wiki coverage',
      'wiki 통계',
      'dashboard stats',
      'wiki dashboard',
      'coverage dashboard',
      '커버리지',
      'show wiki coverage',
    ],
    patterns: [
      /dashboard\s*stats/i,
      /wiki\s*(coverage|dashboard|통계)/i,
      /커버리지/i,
      /show\s+(wiki\s+)?coverage/i,
    ],
    minScore: 4,
    hint: 'Wiki/dashboard statistics JSON',
  },

  // ── Session ──
  {
    id: 'spawn_session',
    category: 'session',
    keywords: [
      'spawn session',
      'spawn_session',
      '세션 생성',
      '세션 띄',
      '병렬 세션',
      '자식 세션',
      'child session',
      '에이전트 실행',
      '서브 에이전트',
      'start session',
      'child agent',
      'run a child agent',
      '자식 에이전트',
    ],
    patterns: [
      /세션\s*(생성|띄|spawn|시작)/i,
      /spawn\s+(a\s+|the\s+)?session/i,
      /start\s+(a\s+|the\s+)?(child\s+)?session/i,
      /run\s+(a\s+|the\s+)?child\s+agent/i,
      /자식\s*에이전트/i,
      /병렬\s*(세션|에이전트)/i,
    ],
    weight: 2,
    textParam: 'task',
    hint: 'Spawn isolated child AI session',
  },
  {
    id: 'check_inbox',
    category: 'session',
    keywords: [
      'check inbox',
      'check_inbox',
      '인박스',
      'inbox 확인',
      '세션 결과',
      '결과 poll',
      'poll inbox',
      'poll session results',
    ],
    patterns: [
      /check\s+(my\s+|the\s+)?inbox/i,
      /poll\s+(the\s+)?inbox/i,
      /poll\s+session\s+results?/i,
      /인박스\s*(확인|조회)?/i,
      /세션\s*결과/i,
    ],
    weight: 2,
    hint: 'Poll child session results',
  },
  {
    id: 'list_sessions',
    category: 'session',
    keywords: [
      'list sessions',
      'list_sessions',
      '세션 목록',
      '세션 리스트',
      'running sessions',
      'show sessions',
    ],
    minScore: 4,
    hint: 'List all sessions',
  },
  {
    id: 'get_session',
    category: 'session',
    keywords: ['get session', 'get_session', '세션 상태', 'session status', 'sess_'],
    patterns: [/sess_[a-z0-9]+/i],
    minScore: 4,
    hint: 'Get session status and logs',
  },
  {
    id: 'close_session',
    category: 'session',
    keywords: [
      'close session',
      'close_session',
      '세션 종료',
      '세션 kill',
      '세션 닫',
      'kill session',
      '세션 죽여',
    ],
    patterns: [
      /kill\s+(the\s+)?session/i,
      /close\s+(the\s+)?session/i,
      /세션\s*(종료|닫|kill|죽여)/i,
    ],
    minScore: 4,
    hint: 'Kill and remove session',
  },
  {
    id: 'send_message',
    category: 'session',
    keywords: [
      'send message',
      'send_message',
      '세션 메시지',
      '세션에 전달',
      'instruction queue',
      'message session',
      '세션에 메시지',
    ],
    patterns: [/send\s+(a\s+|the\s+)?message\s+to\s+(the\s+)?session/i, /세션에\s*(메시지|전달)/i],
    minScore: 5,
    textParam: 'message',
    hint: 'Queue instruction for session',
  },
  {
    id: 'report_result',
    category: 'session',
    keywords: ['report result', 'report_result', '결과 보고', '세션 보고', 'report session result'],
    patterns: [/report\s+(the\s+)?(session\s+)?result/i, /결과\s*보고/i],
    minScore: 5,
    hint: 'Child reports result to inbox',
  },
  {
    id: 'synthesize_results',
    category: 'session',
    keywords: [
      'synthesize',
      'synthesize_results',
      '결과 합성',
      '세션 합성',
      '결과 요약',
      'merge results',
      'synthesize results',
      '결과 합쳐',
      'merge session results',
    ],
    patterns: [
      /merge\s+(session\s+)?results?/i,
      /결과\s*(합성|합쳐|요약)/i,
      /combine\s+(the\s+)?results?/i,
    ],
    weight: 1,
    minScore: 4,
    hint: 'Synthesize child/DAG results',
  },

  // ── DAG ──
  {
    id: 'plan_task',
    category: 'dag',
    keywords: [
      'plan task',
      'plan_task',
      '작업 계획',
      '계획 세우',
      '태스크 분해',
      'decompose',
      'DAG 계획',
      'break down task',
      'create plan',
      '태스크 쪼개',
      'break into tasks',
    ],
    patterns: [
      /계획\s*(세|짜|만들)/i,
      /plan\s+(a\s+|the\s+)?task/i,
      /break\s+(this\s+|it\s+)?down\s+into\s+tasks?/i,
      /break\s+down\s+(this\s+|the\s+)?task/i,
      /decompose\s+(the\s+)?task/i,
      /태스크\s*(분해|쪼개)/i,
    ],
    weight: 2,
    textParam: 'title',
    hint: 'Create plan and suggested DAG stubs',
  },
  {
    id: 'execute_dag',
    category: 'dag',
    keywords: [
      'execute dag',
      'execute_dag',
      'DAG 실행',
      'dag 실행',
      '병렬 실행',
      '체크포인트 재개',
      'resume dag',
      'run dag',
      'resume from checkpoint',
      '체크포인트에서 재개',
    ],
    patterns: [
      /dag\s*(실행|execute)/i,
      /execute\s+(the\s+)?dag/i,
      /run\s+(the\s+)?dag/i,
      /resume\s+(the\s+)?dag/i,
      /resume\s+from\s+checkpoint/i,
      /체크포인트\s*(에서\s*)?재개/i,
    ],
    weight: 2,
    hint: 'Execute DAG (needs tasks from plan_task)',
  },

  // ── Ops ──
  {
    id: 'run_doctor',
    category: 'ops',
    keywords: [
      'run_doctor',
      'run doctor',
      'aio doctor',
      '프로젝트 진단',
      '헬스체크',
      'health check',
      '셋업 확인',
      'setup check',
      'project diagnosis',
      '설치 확인',
      '설치 상태 확인',
      'aio 진단',
    ],
    patterns: [
      /aio\s*(doctor|진단)/i,
      /run\s+(the\s+)?doctor/i,
      /프로젝트\s*진단/i,
      /설치\s*(상태\s*)?확인/i,
      /health\s*check/i,
      /project\s+(health|diagnosis|onboarding\s+check)/i,
      /is\s+my\s+setup\s+ok/i,
      /setup\s+ok\??/i,
    ],
    weight: 2,
    minScore: 4,
    hint: 'Run project health / onboarding diagnostic',
  },
  {
    id: 'request_approval',
    category: 'ops',
    keywords: [
      'request_approval',
      'request approval',
      '승인 요청',
      '승인 필요',
      'human in the loop',
      'need approval',
      'need human approval',
      '사람 승인',
    ],
    patterns: [
      /request\s+(an?\s+)?approval/i,
      /need\s+(human\s+)?approval/i,
      /승인\s*(요청|필요)/i,
      /사람\s*승인/i,
    ],
    minScore: 4,
    textParam: 'action',
    hint: 'Create approval gate',
  },
  {
    id: 'resolve_approval',
    category: 'ops',
    keywords: [
      'resolve approval',
      'resolve_approval',
      '승인 처리',
      '승인 거부',
      'approve request',
      'reject approval',
    ],
    minScore: 5,
    hint: 'Approve or reject pending approval',
  },
  {
    id: 'list_approvals',
    category: 'ops',
    keywords: [
      'list approvals',
      'list_approvals',
      '승인 목록',
      'pending approval',
      'approval list',
      'show pending approvals',
    ],
    patterns: [/(list|show)\s+(pending\s+)?approvals?/i, /승인\s*목록/i],
    minScore: 4,
    hint: 'List approval requests',
  },
  {
    id: 'get_events',
    category: 'ops',
    keywords: [
      'get_events',
      '이벤트 로그',
      'events.jsonl',
      'observability',
      '로그 조회',
      'get events',
      'event log',
      'show events',
    ],
    minScore: 4,
    hint: 'Recent orchestrator events',
  },
  {
    id: 'list_worktrees',
    category: 'ops',
    keywords: [
      'list_worktrees',
      'list worktrees',
      '워크트리',
      'worktree 목록',
      'show worktrees',
      'git worktrees',
      'list git worktrees',
    ],
    patterns: [/list\s+(git\s+)?worktrees?/i, /show\s+(git\s+)?worktrees?/i, /워크트리\s*목록/i],
    minScore: 4,
    hint: 'List git worktrees',
  },
  {
    id: 'remove_worktree',
    category: 'ops',
    keywords: [
      'remove worktree',
      'remove_worktree',
      '워크트리 삭제',
      'worktree 제거',
      'delete worktree',
    ],
    patterns: [
      /remove\s+(the\s+)?worktree/i,
      /delete\s+(the\s+)?worktree/i,
      /워크트리\s*(삭제|제거)/i,
    ],
    minScore: 5,
    hint: 'Remove aio session worktree',
  },

  // ── Branch ──
  {
    id: 'scan_issues',
    category: 'branch',
    keywords: [
      'scan issues',
      'scan_issues',
      'TODO 스캔',
      'FIXME',
      '이슈 스캔',
      '코드 스캔',
      'rg 스캔',
      'scan todos',
      'todo scan',
      'branch hunt scan',
    ],
    patterns: [
      /todo\s*스캔/i,
      /scan\s+(for\s+)?(issues|todos?|fixme)/i,
      /branch\s*hunt\s*scan/i,
      /scan\s+(the\s+)?codebase/i,
    ],
    weight: 2,
    hint: 'Scan codebase for TODO/FIXME/HACK',
  },
  {
    id: 'collect_results',
    category: 'branch',
    keywords: [
      'collect results',
      'collect_results',
      'branch 결과',
      'hunt 결과 수집',
      '결과 수집',
      'collect hunt results',
      'branch hunt 결과',
    ],
    minScore: 5,
    hint: 'Collect branch-hunt results',
  },
  {
    id: 'get_branch_status',
    category: 'branch',
    keywords: [
      'branch status',
      'get_branch_status',
      'branch hunt 상태',
      'hunt 상태',
      '브랜치 상태',
      '헌트 상태',
      'branch hunt status',
    ],
    patterns: [/branch\s*(hunt\s+)?status/i, /(브랜치|헌트)\s*상태/i],
    weight: 2,
    minScore: 5,
    hint: 'Branch hunt status summary',
  },

  // ── Static Analysis ──
  {
    id: 'analyze_codebase',
    category: 'harness',
    keywords: [
      'analyze_codebase',
      '코드 분석',
      '정적 분석',
      'static analysis',
      '코드 그래프',
      'code graph',
      '분석 실행',
      'run analysis',
      '소스 분석',
      '소스코드 분석',
      'analyze code',
      '소스 파싱',
      'source parse',
      '코드 구조 분석',
    ],
    patterns: [
      /코드\s*분석\s*(실행|해|시작)/i,
      /analyze\s+(the\s+)?(codebase|code|source)/i,
      /정적\s*분석/i,
      /static\s+analysis/i,
      /code\s+graph/i,
      /코드\s*그래프/i,
    ],
    weight: 2,
    minScore: 4,
    textParam: 'message',
    hint: 'Static analysis: code graph, routes, data models',
  },
  {
    id: 'query_code_graph',
    category: 'harness',
    keywords: [
      'query_code_graph',
      '코드 그래프 질의',
      '심볼 검색',
      'symbol search',
      '호출 추적',
      'call trace',
      '호출하는 곳',
      '어디서 호출',
      '어디서 사용',
      '함수 호출',
      '함수 찾',
      'find callers',
      'find callees',
      '심볼 찾',
      '의존성 추적',
      'dependency trace',
      '코드 검색',
    ],
    patterns: [
      /(호출|caller|callee|호출하는|사용하는)\s*(곳|위치|찾|검색)/i,
      /find\s+(callers|callees|usages|references)\s+of/i,
      /코드\s*그래프\s*(질의|검색)/i,
      /query\s+(code\s+)?graph/i,
      /symbol\s*(search|lookup|찾)/i,
      /함수\s*(호출|찾|검색)/i,
    ],
    weight: 2,
    minScore: 4,
    textParam: 'query',
    hint: 'Query code graph: symbols, callers, callees, routes',
  },
  {
    id: 'generate_sot',
    category: 'harness',
    keywords: [
      'generate_sot',
      '백과사전',
      'encyclopedia',
      'SOT 생성',
      '서비스 백과사전',
      'service encyclopedia',
      'source of truth',
      'SOT',
      '자동 문서화',
      'auto documentation',
      '코드 문서 생성',
      'generate encyclopedia',
    ],
    patterns: [
      /(서비스\s*)?백과사전\s*(생성|만들)/i,
      /generate\s+(the\s+)?(sot|encyclopedia|source\s+of\s+truth)/i,
      /service\s+encyclopedia/i,
      /sot\s*(생성|generate)/i,
    ],
    weight: 2,
    minScore: 5,
    hint: 'Generate service encyclopedia (SOT) from code analysis',
  },
  {
    id: 'code_graph_status',
    category: 'harness',
    keywords: ['code_graph_status', '분석 상태', 'analysis status', '분석 현황', 'graph status'],
    patterns: [/분석\s*(상태|현황)/i, /(code\s+)?graph\s+status/i],
    minScore: 4,
    hint: 'Show last analysis status',
  },

  // ── SDD ──
  {
    id: 'sdd_spec',
    category: 'harness',
    keywords: [
      'sdd_spec',
      'sdd spec',
      'SDD 스펙',
      '명세 생성',
      'PRD 생성',
      'spec 생성',
      'create spec',
      '스펙 작성',
      '요구사항 명세',
      'product requirement',
      'SDD 생성',
    ],
    patterns: [
      /sdd\s*(스펙|spec)\s*(생성|만들|작성)/i,
      /(스펙|spec|prd|명세)\s*(생성|만들|작성)/i,
      /create\s+(an?\s+)?(sdd\s+)?spec/i,
      /product\s*requirements?\s*doc/i,
    ],
    weight: 2,
    minScore: 5,
    textParam: 'message',
    hint: 'Create SDD spec (PRD + User Stories)',
  },
  {
    id: 'sdd_design',
    category: 'harness',
    keywords: [
      'sdd_design',
      'sdd design',
      '시스템 디자인',
      'system design',
      'SDD 디자인',
      '기술 설계',
      'technical design',
      '설계 생성',
      'create design',
    ],
    patterns: [
      /sdd\s*(디자인|design)\s*(생성|만들)/i,
      /시스템\s*(디자인|설계)\s*(생성|만들)/i,
      /create\s+(an?\s+)?(system\s+)?design/i,
      /기술\s*설계\s*(생성|만들)/i,
    ],
    weight: 2,
    minScore: 5,
    hint: 'Create system design from approved spec',
  },
  {
    id: 'sdd_tasks',
    category: 'harness',
    keywords: [
      'sdd_tasks',
      'sdd tasks',
      'SDD 태스크',
      'implementation tasks',
      '구현 태스크',
      '태스크 생성',
      '작업 목록',
      'generate tasks',
      'create tasks',
    ],
    patterns: [
      /sdd\s*(태스크|tasks?)\s*(생성|만들)/i,
      /(구현\s*)?태스크\s*(생성|만들)/i,
      /generate\s+(implementation\s+)?tasks?/i,
    ],
    weight: 2,
    minScore: 5,
    hint: 'Generate implementation tasks from approved design',
  },
  {
    id: 'sdd_approve',
    category: 'ops',
    keywords: ['sdd_approve', '스펙 승인', 'approve spec', 'SDD 승인', 'sdd approve'],
    patterns: [/스펙\s*(승인|approve)/i, /approve\s+(the\s+)?(sdd\s+)?spec/i],
    minScore: 5,
    hint: 'Approve SDD spec or design',
  },
  {
    id: 'sdd_approve_design',
    category: 'ops',
    keywords: [
      'sdd_approve_design',
      '디자인 승인',
      'approve design',
      '설계 승인',
      'design approve',
    ],
    patterns: [/디자인\s*(승인|approve)/i, /approve\s+(the\s+)?design/i, /설계\s*승인/i],
    minScore: 5,
    hint: 'Approve SDD design with evidence',
  },
  {
    id: 'sdd_status',
    category: 'harness',
    keywords: [
      'sdd_status',
      'sdd status',
      'SDD 상태',
      'SDD 현황',
      '파이프라인 상태',
      'pipeline status',
    ],
    patterns: [/sdd\s*(상태|status)/i, /SDD\s*(파이프라인\s*)?(상태|현황)/i],
    minScore: 4,
    hint: 'Show SDD pipeline status',
  },

  // ── Impact Analysis ──
  {
    id: 'impact_analyze',
    category: 'harness',
    keywords: [
      'impact_analyze',
      '영향도 분석',
      'impact analysis',
      '영향 분석',
      '변경 영향',
      'change impact',
      'impacts of change',
      '영향도 평가',
      'impact assessment',
      'dossier',
      '영향도',
      'what is affected',
      '무엇이 영향',
    ],
    patterns: [
      /영향도\s*(분석|평가|조사)/i,
      /impact\s+(analysis|assessment|of\s+change)/i,
      /변경\s*영향/i,
      /what\s+(is\s+)?affected/i,
      /영향\s*받/i,
    ],
    weight: 2,
    minScore: 4,
    textParam: 'change_description',
    hint: 'Analyze change impact → evidence dossier',
  },
  {
    id: 'impact_dossier_get',
    category: 'harness',
    keywords: [
      'impact_dossier_get',
      'dossier 조회',
      'dossier detail',
      'dossier 상세',
      '영향도 상세',
      'get dossier',
      'dossier 결과',
    ],
    patterns: [/dossier\s*(조회|상세|detail|get)/i, /영향도\s*상세/i],
    minScore: 5,
    hint: 'Get impact dossier details',
  },
  {
    id: 'impact_dossier_list',
    category: 'harness',
    keywords: [
      'impact_dossier_list',
      'dossier 목록',
      'dossier list',
      '영향도 목록',
      'list dossier',
      'show dossiers',
    ],
    patterns: [/dossier\s*(목록|list)/i, /영향도\s*목록/i, /list\s+dossiers?/i],
    minScore: 4,
    hint: 'List all impact dossiers',
  },

  // ── Memory ──
  {
    id: 'memory_set',
    category: 'knowledge',
    keywords: [
      'memory_set',
      '메모 저장',
      '메모 기록',
      'save memory',
      'record memory',
      '메모 남기',
      '왜 이렇게',
      '이유 메모',
      'constraint 메모',
      '메모 추가',
      'add memory',
      'anchor memory',
    ],
    patterns: [
      /메모\s*(저장|기록|남기|추가)/i,
      /save\s+(a\s+)?memory/i,
      /record\s+(a\s+)?(why|correction|constraint|context)/i,
      /왜\s*이렇게\s*했/i,
    ],
    weight: 1,
    minScore: 4,
    textParam: 'content',
    hint: 'Save a memory (why/correction/constraint/context)',
  },
  {
    id: 'memory_get',
    category: 'knowledge',
    keywords: [
      'memory_get',
      '메모 조회',
      '메모 읽',
      'get memory',
      'read memory',
      '메모 보',
      '저장된 메모',
      'anchor 메모',
    ],
    patterns: [/메모\s*(조회|읽|보|가져)/i, /get\s+(the\s+)?memor(y|ies)/i, /read\s+memor(y|ies)/i],
    minScore: 4,
    hint: 'Get memories for an anchor',
  },
  {
    id: 'memory_search',
    category: 'knowledge',
    keywords: [
      'memory_search',
      '메모 검색',
      'search memory',
      '메모 찾',
      'memories about',
      '메모 내용',
      'find memory',
    ],
    patterns: [
      /메모\s*(검색|찾)/i,
      /search\s+(the\s+)?memor(y|ies)/i,
      /find\s+memor(y|ies)\s+(about|containing)/i,
    ],
    weight: 1,
    textParam: 'query',
    hint: 'Search memory contents',
  },
  {
    id: 'memory_update',
    category: 'knowledge',
    keywords: [
      'memory_update',
      '메모 수정',
      '메모 업데이트',
      'update memory',
      'edit memory',
      '메모 변경',
    ],
    patterns: [/메모\s*(수정|업데이트|변경|edit)/i, /update\s+(the\s+)?memory/i],
    minScore: 5,
    hint: 'Update existing memory',
  },
  {
    id: 'memory_delete',
    category: 'knowledge',
    keywords: ['memory_delete', '메모 삭제', 'delete memory', 'remove memory', '메모 지'],
    patterns: [/메모\s*(삭제|지|remove)/i, /delete\s+(the\s+)?memory/i],
    minScore: 5,
    hint: 'Delete a memory',
  },

  // ── Multi-Repo ──
  {
    id: 'repo_register',
    category: 'ops',
    keywords: [
      'repo_register',
      '레포 등록',
      '저장소 등록',
      'register repo',
      '레포 추가',
      'add repository',
      'repository 등록',
      '멀티 레포',
      'multi repo',
    ],
    patterns: [
      /레포\s*(등록|추가|register)/i,
      /저장소\s*(등록|추가)/i,
      /register\s+(a\s+)?(repo|repository)/i,
      /add\s+(a\s+)?(repo|repository)/i,
    ],
    minScore: 5,
    hint: 'Register a repository for cross-repo analysis',
  },
  {
    id: 'repo_list',
    category: 'ops',
    keywords: [
      'repo_list',
      '레포 목록',
      '저장소 목록',
      'list repos',
      'list repositories',
      '등록된 레포',
      'registered repos',
    ],
    patterns: [/레포\s*목록/i, /(list|show)\s+(registered\s+)?(repos|repositories)/i],
    minScore: 4,
    hint: 'List registered repositories',
  },
  {
    id: 'cross_repo_query',
    category: 'harness',
    keywords: [
      'cross_repo_query',
      '전체 레포 검색',
      '크로스 레포',
      'cross repo',
      'multi-repo search',
      '전체 저장소 검색',
      '레포 간 검색',
      'cross repository',
      'search all repos',
    ],
    patterns: [
      /(전체\s*)?레포\s*(간\s*)?(검색|찾)/i,
      /cross[-\s]?repo\s*(query|search)/i,
      /search\s+(all\s+)?(repos|repositories)/i,
      /저장소\s*(간\s*)?검색/i,
    ],
    weight: 2,
    minScore: 4,
    textParam: 'query',
    hint: 'Search across all registered repositories',
  },
  {
    id: 'repo_remove',
    category: 'ops',
    keywords: [
      'repo_remove',
      '레포 제거',
      '레포 삭제',
      'remove repo',
      'delete repo',
      '저장소 제거',
    ],
    patterns: [/레포\s*(제거|삭제)/i, /remove\s+(a\s+)?(repo|repository)/i, /저장소\s*제거/i],
    minScore: 5,
    hint: 'Remove a registered repository',
  },

  // ── Knowledge ──
  {
    id: 'recall_knowledge',
    category: 'knowledge',
    keywords: [
      'recall_knowledge',
      '지식 검색',
      'semantic search',
      '의미 검색',
      'recall knowledge',
      'search knowledge',
      '기억에서',
      'search my notes',
    ],
    patterns: [
      /지식\s*(검색|찾|조회)/i,
      /recall\s*(knowledge|memory)/i,
      /search\s+(the\s+)?knowledge/i,
      /semantic\s+search/i,
      /기억에서\s*(찾|검색|조회)/i,
      /search\s+(my\s+|the\s+)?notes/i,
    ],
    weight: 1,
    minScore: 4,
    textParam: 'query',
    hint: 'Semantic search knowledge base',
  },
  {
    id: 'store_knowledge',
    category: 'knowledge',
    keywords: [
      'store knowledge',
      'store_knowledge',
      '지식 저장',
      'vault 저장',
      'note 저장',
      'save knowledge',
      '노트에 저장',
      'save this note',
    ],
    patterns: [
      /store\s+(this\s+)?knowledge/i,
      /지식\s*저장/i,
      /save\s+(to\s+)?(the\s+)?vault/i,
      /save\s+(this\s+)?note/i,
      /노트에\s*저장/i,
    ],
    minScore: 4,
    textParam: 'query',
    hint: 'Save to Obsidian vault',
  },
]

export const ALL_TOOL_IDS = TOOL_KEYWORDS.map((t) => t.id)

/**
 * ASCII tokens need word boundaries so "brainstorm" does not match inside "brainstorm_design".
 * Underscore counts as part of the token (snake_case tool ids / identifiers).
 * Short tokens (≤3) keep the same rule; Korean/mixed keywords still use substring includes.
 */
function keywordMatches(lowerText: string, keyword: string): boolean {
  const k = keyword.toLowerCase()
  if (!k) return false
  if (/^[a-z0-9]+(?:[\s-][a-z0-9]+)*$/i.test(k)) {
    return new RegExp(`(?:^|[^a-z0-9_])${escapeRegExp(k)}(?:[^a-z0-9_]|$)`, 'i').test(lowerText)
  }
  return lowerText.includes(k)
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/**
 * Score a tool against free text.
 * Weight is a bonus only after at least one keyword/pattern hit — never a catch-all.
 */
export function scoreToolMatch(
  def: ToolKeywordDef,
  text: string
): { score: number; matched: string[] } {
  const lower = text.toLowerCase()
  let score = 0
  const matched: string[] = []

  for (const kw of def.keywords) {
    if (keywordMatches(lower, kw)) {
      score += Math.max(kw.length, 2)
      matched.push(kw)
    }
  }
  for (const re of def.patterns || []) {
    if (re.test(text)) {
      score += 12
      // Store a marker so extractFreeText can re-apply the pattern (not a literal source string)
      matched.push(`re:${re.source}`)
    }
  }
  // Explicit tool id mention (e.g. "brainstorm_design …") — whole id only
  if (new RegExp(`(?:^|[^a-z0-9])${escapeRegExp(def.id)}(?:[^a-z0-9]|$)`, 'i').test(text)) {
    score += Math.max(def.id.length, 8)
    matched.push(def.id)
  }

  if (matched.length === 0) {
    return { score: 0, matched: [] }
  }

  score += def.weight || 0
  return { score, matched }
}

export function findToolDef(id: string): ToolKeywordDef | undefined {
  return TOOL_KEYWORDS.find((t) => t.id === id)
}

/** Compact rules embedded in Cursor hook (pattern source strings) */
export function hookKeywordRules(): Array<{ tool: string; sources: string[] }> {
  return TOOL_KEYWORDS.filter((t) => t.id !== 'aio_prompt').map((t) => ({
    tool: t.id,
    sources: [
      ...t.keywords.slice(0, 6).map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')),
      ...(t.patterns?.map((p) => p.source) || []),
    ],
  }))
}
